### ISSUE TITLE
`rescue in start': Could not establish TCP connection to any of the configured hosts

### ISSUE THREAD

**Issue by samerzmd** [Rudy-Zidan/jobi#9]
```
/usr/local/bundle/gems/bunny-2.17.0/lib/bunny/session.rb:343:in `rescue in start': Could not establish TCP connection to any of the configured hosts (Bunny::TCPConnectionFailedForAllHosts)
        from /usr/local/bundle/gems/bunny-2.17.0/lib/bunny/session.rb:315:in `start'
        from /usr/local/bundle/gems/jobi-0.2.1/lib/jobi/clients/rabbitmq.rb:17:in `initialize'
        from /usr/local/bundle/gems/jobi-0.2.1/lib/jobi.rb:31:in `new'
        from /usr/local/bundle/gems/jobi-0.2.1/lib/jobi.rb:31:in `session'
        from /usr/local/bundle/gems/jobi-0.2.1/lib/jobi/job.rb:63:in `join_queue'
        from /usr/local/bundle/gems/jobi-0.2.1/lib/jobi/job.rb:34:in `consume_messages'
        from /usr/local/bundle/gems/jobi-0.2.1/lib/jobi.rb:60:in `block in start'
        from /usr/local/bundle/gems/jobi-0.2.1/lib/jobi.rb:59:in `each'
        from /usr/local/bundle/gems/jobi-0.2.1/lib/jobi.rb:59:in `start'
        from /usr/local/bundle/gems/jobi-0.2.1/lib/jobi.rb:23:in `configure'
        from /myapp/config/initializers/jobi.rb:4:in `<top (required)>'
```

**Comment by samerzmd** [comment]
after upgrading to 0.2.1

**Comment by Rudy-Zidan** [comment]
Do you have a rabbitmq installed and running ?
What is your configuration is it the default one?

**Comment by Rudy-Zidan** [comment]
Make sure you provides the correct credential in the Jobi.configure block if you are using a custom credentials (username & password).
